// 種子資料：從 data/seed.json 原封不動轉成 Apps Script 常數（此檔只放資料，不放邏輯）。
// setupSheets() 用這份資料建立 questions／study_groups／practice_days／day_questions／question_integrations／settings，
// 不建立 participants（真實成員請用 importMembers() 另外匯入，見 DEPLOY.md）。
// 若之後 data/seed.json 的題目或題組內容有更新，這裡也要跟著手動同步一份。

var SEED_DATA_ = {
  questions: [
    { id: 'q01', number: 1, title: '頸椎退行性變化' },
    { id: 'q02', number: 2, title: '腰肌急性扭傷／閃腰' },
    { id: 'q03', number: 3, title: '慢性腰部損傷' },
    { id: 'q04', number: 4, title: '腰椎滑脫' },
    { id: 'q05', number: 5, title: '第三腰椎橫突過長' },
    { id: 'q06', number: 6, title: '腰骶部病變' },
    { id: 'q07', number: 7, title: '骶髂關節損傷' },
    { id: 'q08', number: 8, title: '腕溝管損傷' },
    { id: 'q09', number: 9, title: '膝關節髕下脂肪墊損傷' },
    { id: 'q10', number: 10, title: '踝關節急性扭傷' },
    { id: 'q11', number: 11, title: '踝溝管損傷' },
    { id: 'q12', number: 12, title: '足跟退行性變化' },
    { id: 'q13', number: 13, title: '腰椎退行性變化' },
    { id: 'q14', number: 14, title: '強直性脊椎炎' },
    { id: 'q15', number: 15, title: '髖關節骨關節炎' },
    { id: 'q16', number: 16, title: '肩關節周圍炎／五十肩' },
    { id: 'q17', number: 17, title: '肱骨外上髁炎／網球肘' },
    { id: 'q18', number: 18, title: '肱骨內上髁炎' },
    { id: 'q19', number: 19, title: '腕部橈側伸腕肌腱周圍炎' },
    { id: 'q20', number: 20, title: '膝關節滑膜炎' },
    { id: 'q21', number: 21, title: '跟腱炎' },
    { id: 'q22', number: 22, title: '類風濕性關節炎－上肢' },
    { id: 'q23', number: 23, title: '類風濕性關節炎－下肢' },
    { id: 'q24', number: 24, title: '臂神經叢麻痺' },
    { id: 'q25', number: 25, title: '正中神經麻痺' },
    { id: 'q26', number: 26, title: '尺神經麻痺' },
    { id: 'q27', number: 27, title: '橈神經麻痺' },
    { id: 'q28', number: 28, title: '腓總神經麻痺' },
    { id: 'q29', number: 29, title: '顏面神經麻痺' },
    { id: 'q30', number: 30, title: '半身不遂／中風－上肢' },
    { id: 'q31', number: 31, title: '半身不遂／中風－下肢' },
    { id: 'q32', number: 32, title: '頭痛' },
    { id: 'q33', number: 33, title: '三叉神經痛' },
    { id: 'q34', number: 34, title: '肋間神經痛' },
    { id: 'q35', number: 35, title: '坐骨神經痛／腰椎間盤突出' },
    { id: 'q36', number: 36, title: '梨狀肌病變／神經痛' },
    { id: 'q37', number: 37, title: '急性頸部軟組織痙攣／落枕' },
    { id: 'q38', number: 38, title: '肩頸凝' },
    { id: 'q39', number: 39, title: '便秘' },
    { id: 'q40', number: 40, title: '失眠' },
  ],
  groups: [
    { id: 'g1', name: '第一練習群組' },
  ],
  practiceDays: [
    {
      id: 'd1',
      groupId: 'g1',
      order: 1,
      label: '第一天',
      theme: '神經類',
      questionIds: ['q24', 'q25', 'q26', 'q27', 'q28', 'q35', 'q36'],
    },
    {
      id: 'd2',
      groupId: 'g1',
      order: 2,
      label: '第二天',
      theme: '頸肩與上肢',
      questionIds: ['q01', 'q16', 'q17', 'q18', 'q19', 'q37', 'q38'],
    },
    {
      id: 'd3',
      groupId: 'g1',
      order: 3,
      label: '第三天',
      theme: '腰臀、髖',
      questionIds: ['q02', 'q03', 'q04', 'q05', 'q06', 'q07', 'q13', 'q15'],
    },
    {
      id: 'd4',
      groupId: 'g1',
      order: 4,
      label: '第四天',
      theme: '特殊題',
      questionIds: ['q22', 'q23', 'q29', 'q30', 'q31', 'q32', 'q33', 'q34', 'q39', 'q40'],
    },
    {
      id: 'd5',
      groupId: 'g1',
      order: 5,
      label: '第五天',
      theme: '補充題',
      questionIds: ['q08', 'q09', 'q10', 'q11', 'q12', 'q14', 'q20', 'q21'],
    },
  ],
  settings: {
    g1: {
      selectionLimit: 2,
      currentDayId: 'd1',
      currentRound: 1,
      staleDays: 14,
    },
  },
  questionIntegrations: [],
};
